language: ruby
rvm:
- 2.5.0
script:
- bundle exec rspec spec
services:
- postgresql
before_install:
- gem install bundler
before_script:
- bin/rails db:create
- bin/rails db:migrate
deploy:
  provider: heroku
  api_key:
    secure: oZb6Z4A0JcQSp+ivDD/eyhxodHis1B5ISXp14KzUWEwbb6ytIjN69JYjZnD6seS4NXv9S0zZnqNSCZ+RdW+u3s7qfoG3lcAl3wdeVBPQBV4PFAl0wrrdQwc2Nop4zGTLSSyVLjpmRIpqAt2SptbiVssM8uaJmA15gDT2OOfo+5p8E/6wh/ReYuUmyXg26UEEd9JscY7bqz9j5PJC8jM4XpsTzxsD6uYdK9e0B29bj0dnXysezz0lzZKMWbafY7/ICzXFEAoki9ftHyhUrz99yCRiwr7k1TMI9vlr2qwMgDgo8WRCUnMixX8mtXR4TODrYdxJsp5zft5WzoLUl90GBb0VNa7b9umbel69l9ysTMBjcMH6yaEUa0bY6ECJLXsWp3sW/Ict4onBdoazdn00sjNrRpEx5Sju5GsNo/rvrUUiLLvQlgDYWWqgJbO7+OY+mI55+eMuNCMyBUdbQUTsSIhaujRy/lWcFo8zmUAyxvG3AAY+XzSKayvcatYpJYhWdN0ft/HNOAu4HDx+DKD+M+L67MqG2cnsnY9BLDX/cY2SnikK1qWXP5XQizKlM3BRGufzhN0XYWo+bp6+hnw/bbV0tPvezW7lxXOxKGey0HqKIb6geYymaFV/QlrGA7mx6+crepA6C2+HgDbi05R8mSOqmldfZuxT0kZy8r/XxcM=
  app: maln-acebook
  on:
    repo: blarvin/TEAM-MALN-ACEBOOK
