language: ruby
rvm:
- 2.5.0
script:
- bundle exec rspec spec
services:
- postgresql
before_install:
- gem install bundler
before_script:
- bin/rails db:create
- bin/rails db:migrate
deploy:
  provider: heroku
  api_key:
    secure: nUowqXR/HJi/0+PWa/c1uZ9hBkFHW0F6fKpsQ7WcswuXRKenGjrbjIf4vRO3BxH85xXStJkBsOd0lSu+3b05XUbsLy20U7YwAMQjwcn+LzVg4MoJ6+/Mo2uIIfH563K8eglEwDUHMi6CzVKjJ7kC81FUkcn1gED8YFPFzNIhTTrhiG56r8puLCxXbtUe1OxJLbD5D6mUaWyzGWgurZWJLzKA8yzw/XPFxAHTIQQFzslfyJVdsBgfU49p4XmFgLTaGjZueiMwaZNR4K+zwYaVOBkomxnHUIi9nMgRqhI8zPxbEZWL2WovGI4Cvz8YRgb4dyu39GLcF9UN6Fvn3hhsYVv/anjV0mUoYIsZvYh1CIw9zrxqjWQ/SI4SUw4Xpsz3ezClcHNm65UY8HQM5B3nr+TNYQh7b4KwaMuv9+R4B7369IncQrDh7kvxBO37eIHDn/OnOkt8XfudBOMeDYvHxFr0N8WBHS+Vz/OM/gbBT03sXe4QuW6DwZQeJROuDl6ZoWWB/3hCSQ6WGMpJy/c5GWilcah/g5sXXN+Ob2OQ0nTVkMrtdfzEpcvJCVy+SPUJtqGwleTVpE4l4vC3KpJvJP286iDkoOxkZHdQj4JCvF46GBhWxR1lT0L0ce68lqJ11mNYEMD6ybBmvy8bLVqh/ffVfRaUTOf9MWfocGnPvBk=
  app: TEAM-MALN-ACEBOOK
  on:
    repo: blarvin/TEAM-MALN-ACEBOOK
